var annotated_dup =
[
    [ "Geometry", "d2/d1a/namespaceGeometry.html", [
      [ "Vector2D", "dc/d33/structGeometry_1_1Vector2D.html", "dc/d33/structGeometry_1_1Vector2D" ],
      [ "Point", "d5/d8f/structGeometry_1_1Point.html", "d5/d8f/structGeometry_1_1Point" ],
      [ "Line", "d1/d2a/structGeometry_1_1Line.html", "d1/d2a/structGeometry_1_1Line" ],
      [ "Triangle", "d9/d10/structGeometry_1_1Triangle.html", "d9/d10/structGeometry_1_1Triangle" ]
    ] ],
    [ "Cell", "de/dfd/classCell.html", "de/dfd/classCell" ],
    [ "CellError", "db/d16/classCellError.html", "db/d16/classCellError" ],
    [ "CellOriginBuilder", "df/da6/classCellOriginBuilder.html", "df/da6/classCellOriginBuilder" ],
    [ "CompositeSurface", "d3/d6c/classCompositeSurface.html", "d3/d6c/classCompositeSurface" ],
    [ "CompositeSurfaceError", "d4/d58/classCompositeSurfaceError.html", "d4/d58/classCompositeSurfaceError" ],
    [ "DispersionData", "d4/d8a/structDispersionData.html", "d4/d8a/structDispersionData" ],
    [ "EmitSurface", "d4/de9/classEmitSurface.html", "d4/de9/classEmitSurface" ],
    [ "FuncTimer", "d3/d61/structFuncTimer.html", null ],
    [ "InputManager", "d5/d39/classInputManager.html", "d5/d39/classInputManager" ],
    [ "IntersectError", "db/d99/classIntersectError.html", "db/d99/classIntersectError" ],
    [ "LineError", "dc/d35/classLineError.html", "dc/d35/classLineError" ],
    [ "Material", "d3/d89/classMaterial.html", "d3/d89/classMaterial" ],
    [ "Model", "d6/d18/classModel.html", "d6/d18/classModel" ],
    [ "ModelSimulator", "df/dce/classModelSimulator.html", "df/dce/classModelSimulator" ],
    [ "OutputManager", "d1/d22/classOutputManager.html", "d1/d22/classOutputManager" ],
    [ "OverlapError", "db/d85/classOverlapError.html", "db/d85/classOverlapError" ],
    [ "PeriodicController", "db/d1b/classPeriodicController.html", "db/d1b/classPeriodicController" ],
    [ "PhasorBuilder", "d0/dc3/classPhasorBuilder.html", "d0/dc3/classPhasorBuilder" ],
    [ "Phonon", "d2/db2/classPhonon.html", "d2/db2/classPhonon" ],
    [ "PhononBuilder", "d2/d07/classPhononBuilder.html", "d2/d07/classPhononBuilder" ],
    [ "RelaxationData", "d6/d24/structRelaxationData.html", "d6/d24/structRelaxationData" ],
    [ "Sensor", "d1/dd6/classSensor.html", "d1/dd6/classSensor" ],
    [ "SensorController", "df/d30/classSensorController.html", "df/d30/classSensorController" ],
    [ "SensorInterpreter", "d6/de9/classSensorInterpreter.html", "d6/de9/classSensorInterpreter" ],
    [ "SensorMeasurements", "d5/dca/structSensorMeasurements.html", "d5/dca/structSensorMeasurements" ],
    [ "ShapeError", "df/d46/classShapeError.html", "df/d46/classShapeError" ],
    [ "SteadyStateController", "d6/d6d/classSteadyStateController.html", "d6/d6d/classSteadyStateController" ],
    [ "Surface", "de/d10/classSurface.html", "de/d10/classSurface" ],
    [ "SurfaceOriginBuilder", "d5/dea/classSurfaceOriginBuilder.html", "d5/dea/classSurfaceOriginBuilder" ],
    [ "TableData", "d1/d7e/structTableData.html", "d1/d7e/structTableData" ],
    [ "Timer", "dc/dea/classTimer.html", "dc/dea/classTimer" ],
    [ "TransientController", "da/deb/classTransientController.html", "da/deb/classTransientController" ],
    [ "TransitionSurface", "d4/da5/classTransitionSurface.html", "d4/da5/classTransitionSurface" ],
    [ "TriangleError", "d3/d45/classTriangleError.html", "d3/d45/classTriangleError" ]
];